CREATE DATABASE IF NOT EXISTS PHONESTORE;
USE PHONESTORE;

CREATE TABLE PHONE (
    ID INT AUTO_INCREMENT,
    MODEL VARCHAR(50) NOT NULL,
    MARC VARCHAR(50) NOT NULL,
    SPECS TEXT NOT NULL,
    REGISTER_DATE DATE NOT NULL,
    PHOTO BLOB,
    STATE INT NOT NULL,
    PRICE DECIMAL(10,2) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE INVENTORY (
	ID INT AUTO_INCREMENT,
    ID_PHONE INT NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (ID_PHONE) REFERENCES PHONE(ID)
);

CREATE TABLE VOUCHER(
	ID INT AUTO_INCREMENT,
    DATE DATE NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE PHONE_VOUCHER(
	ID INT AUTO_INCREMENT,
	ID_PHONE INT NOT NULL,
    ID_VOUCHER INT NOT NULL,
    PHONE_QUANTITY INT NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (ID_PHONE) REFERENCES PHONE(ID),
    FOREIGN KEY (ID_VOUCHER) REFERENCES VOUCHER(ID)
);