INSERT INTO PHONE (NAME) VALUES ("Samsung");
INSERT INTO PHONE (NAME) VALUES ("Huawei");
INSERT INTO PHONE (NAME) VALUES ("Apple");
INSERT INTO PHONE (NAME) VALUES ("Xiaomi");
INSERT INTO PHONE (NAME) VALUES ("Nokia");

SELECT ID, NAME FROM PHONE;